# REQUEST
string motion_code                  # codigo (A, B, C, D) segun el movimiento que se quiera hacer
geometry_msgs/Point object_coord    # coordenadas del objeto
float32 radius                      # radio con el que el brazo rodea al punto
---
# RESPONSE
bool move_successful    # ejecucion exitosa?
string message          # mas informacion sobre el resultado
